// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WerkstattApi.Migrations
{
    [DbContext(typeof(WerkstattApiContext))]
    partial class WerkstattApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WerkstattApi.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WerkstattId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WerkstattId");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("WerkstattApi.Models.Werkstatt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Werkstatt");
                });

            modelBuilder.Entity("WerkstattApi.Models.Mitarbeiter", b =>
                {
                    b.HasOne("WerkstattApi.Models.Werkstatt", "Werkstatt")
                        .WithMany()
                        .HasForeignKey("WerkstattId");

                    b.Navigation("Werkstatt");
                });
#pragma warning restore 612, 618
        }
    }
}
